// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmVdcMBeB7BrPTIbPAlBvUojCeTVy9Ka0',
    appId: '1:881386821758:web:0b3c797499d317811aa02f',
    messagingSenderId: '881386821758',
    projectId: 'meal-app-lab',
    authDomain: 'meal-app-lab.firebaseapp.com',
    storageBucket: 'meal-app-lab.firebasestorage.app',
    measurementId: 'G-WC2YVZMHYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNxGWgNkIYAxSdDQD3pp8vPBRkDk432mc',
    appId: '1:881386821758:android:6b4f6a3dbb14a39c1aa02f',
    messagingSenderId: '881386821758',
    projectId: 'meal-app-lab',
    storageBucket: 'meal-app-lab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW9_39qEJdHcfhycFIiZUd7WiJhcwFBrU',
    appId: '1:881386821758:ios:4f101c692dd68fc81aa02f',
    messagingSenderId: '881386821758',
    projectId: 'meal-app-lab',
    storageBucket: 'meal-app-lab.firebasestorage.app',
    iosBundleId: 'com.example.mealAppLab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW9_39qEJdHcfhycFIiZUd7WiJhcwFBrU',
    appId: '1:881386821758:ios:4f101c692dd68fc81aa02f',
    messagingSenderId: '881386821758',
    projectId: 'meal-app-lab',
    storageBucket: 'meal-app-lab.firebasestorage.app',
    iosBundleId: 'com.example.mealAppLab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmVdcMBeB7BrPTIbPAlBvUojCeTVy9Ka0',
    appId: '1:881386821758:web:5d25e385ec4376b21aa02f',
    messagingSenderId: '881386821758',
    projectId: 'meal-app-lab',
    authDomain: 'meal-app-lab.firebaseapp.com',
    storageBucket: 'meal-app-lab.firebasestorage.app',
    measurementId: 'G-XQ58X24EDY',
  );
}
